<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<title>Eksisarkilar</title>
	<meta name="description" content="Ah bu şarkıların gözü kör olsun!...">

	<link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
	<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

	<style>
		body {
			margin: 50px 0 0 0;
			padding: 0;
			width: 100%;
			font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
			text-align: center;
			color: #aaa;
			font-size: 18px;
		}

		h1 {
			color: #719e40;
			letter-spacing: -3px;
			font-family: 'Lato', sans-serif;
			font-size: 100px;
			font-weight: 200;
			margin-bottom: 0;
		}
	</style>
</head>
<body>
<h1>Eksisarkilar</h1>
<div class="container">
	<div class="alert alert-success"><?php echo sprintf( ' "%s" playlisti başarılı bir şekilde oluşturuldu.Dinlemek içın <a href="%s">tıklayın!</a>', PLAYLIST_NAME, $playlist_link ); ?></div>
	<div class="text-center">🎹🎺🎻🎸🎷🥁🎶🤘😍😘</div>
</div>
</body>
</html>
